### ISSUE TITLE
Research Jobgether

### ISSUE THREAD

**Issue by alexpdp7** [remote-es/remotes#102]
https://jobgether.com

**Comment by alexpdp7** [comment]
Sent them an email. You can filter by "contract" "permanent" and "work from" "Spain", but I'm not sure that is a good guarantee.

**Comment by alexpdp7** [comment]
> We are the largest remote job aggregator, our objective is to bring transparency to Remote talents and we make sure that the remote location is correct.
> Some companies hiring anywhere worldwide or in Europe will indeed propose a freelance contract, some others will do it with a permanent contract through Deel, Oyster, etc. 
> This information is not easily accessible, and many companies will sign permanent or freelance contracts pendending on the role and the profile of the candidate. So this information is not transparent.

> In any case, we can guarantee that all companies having "Spain" within their "remote countries" are hiring through permanent contracts.

Maybe we can add them as:

```
* Jobgether [Open positions](https://jobgether.com/search-offers?meta.locations=622a65b3671f2c8b98fac81c) Jobgether is a remote job aggregator. Positions that list explicitly "Spain" in the "remote from"/"remote location allowed" hire through permanent contracts in Spain.
```

I'll send them another email to followup and validate that I understood correctly, but I'll wait to see if @smoya disagrees.

**Comment by smoya** [comment]
> ```
> 
> ```
> 
> 
>     
> 
>   
> 
> I'll send them another email to followup and validate that I understood correctly, but I'll wait to see if @smoya disagrees.

Just an small and nitpick change:

> * Jobgether [Open positions](https://jobgether.com/search-offers?meta.locations=622a65b3671f2c8b98fac81c) Jobgether is a remote job aggregator. Positions that explicitly list "Spain" in the `remote from`/`remote location allowed` field hire through permanent contracts in Spain.

Also, we could add the following query param to the link: `&meta.contractType=CONTRACT_INDEF`. It filters directly by permanent contracts so in case the condition changes in the future, this will still be valid (if I understood correctly).

**Comment by alexpdp7** [comment]
Jobgether says:

> 1. Remote Location :  Europe or Anywhere - The company may offer Freelance position or Permanent Contract, depending on each company policy.
>
> 2. Remote Location : Spain (only, or among a list of countries) - The company is using to hire from Spain will (more than likely) propose Permanent Contracts.

So I sent https://github.com/remote-es/remotes/pull/135 @smoya .
