### ISSUE TITLE
Maybe Delete

### ISSUE THREAD

**Issue by AngelProg02** [remote-es/remotes#107]
Crealsa out maybe, 404 page and not exist on LinkedIn

**Comment by alexpdp7** [comment]
Thanks for the heads up, removed. How did you find out it was closed? Were you using the rest of the listing? (If so, I suppose the rest of links work?)

**Comment by AngelProg02** [comment]
Hey! Yes im using the list, the rest of the list its okay, at least up to letter 'c ' 😂 . I'm sending CV to some companies, if i found some other issues i' ll let you know 👌🏼

Nice job with this 👌🏼👌🏼

**Comment by alexpdp7** [comment]
Awesome, thanks! Good luck!

**Comment by uesteibar** [comment]
yay, good luck with your search @AngelProg02 🍀
