### ISSUE TITLE
Hi! I reviewed the list and sent the CV to the companies that were eligible for the offers. Thank you!

### ISSUE THREAD

**Issue by AngelProg02** [remote-es/remotes#108]
Delitbee -- Deleted
Fotograf.de - Maybe unused, last offer, one year ago
Genialy -- Click and open LinkedIn page, they have "Join us" ---- https://genial.ly/es/unete-al-equipo/#wearehiring
Honeypot -- Out
Hotjar -- Out or not secure?
Hubuc -- Maybe unused, last offer, one year ago
Jeff - Deleted
Justo Seguros -- Deleted
Lana -- ??
nc43|tech -- Deleted
Nucoro -- Deleted
Picker -- ??
Rankia -- Job page deleted
Pulpo -- Link change: https://career.teamtailor.com/ 
Redradix ?? 
SmartTechnologies -- Link change: https://smarttechnologies.hire.trakstar.com/
Splice Machine -- Deleted
Streamloots -- Deleted
Tot-em -- Deleted
XpertAI -- Deleted

**Comment by alexpdp7** [comment]
* Delitbee https://github.com/remote-es/remotes/commit/50afecb2ec5706b3c8bc22d8f2a37d2e2b9c2546

**Comment by alexpdp7** [comment]
Thanks for your review! Good luck with your job hunt!

In the future, don't hesitate to send PRs directly if you want. Also, while looking for a job, if you find other companies, maybe you could also add them here?

**Comment by AngelProg02** [comment]
> Thanks for your review! Good luck with your job hunt!
> 
> In the future, don't hesitate to send PRs directly if you want. Also, while looking for a job, if you find other companies, maybe you could also add them here?

Of course, if i see something interesting, i add them here 😁
