### ISSUE TITLE
Investigate levels.fyi

### ISSUE THREAD

**Issue by alexpdp7** [remote-es/remotes#129]
A member of BcnEng proposes we add:

https://www.levels.fyi/jobs/location/spain?workArrangements=remote

to the "others" section. Actually, this job site looks very good and I think a lot of jobs with that filter meet the requirements of this list.

I think the offers such as this one:

![imagen](https://github.com/remote-es/remotes/assets/1150630/91eb06f2-9451-43c4-8337-abdc70550a2c)

, which list *only* locations in Spain, are likely to be "good". However, I fear that offers like:

![imagen](https://github.com/remote-es/remotes/assets/1150630/32b29e40-22c3-4c04-9888-745224870d53)

may not be- frequently companies hiring in multiple companies require "foreign" employees to be contractors/freelancers.

In other cases, we have contacted the site and asked them for details. For example, https://github.com/remote-es/remotes/issues/102 I just received an answer which is likely negative (I'll update the ticket in the meantime).

Pinging the person who reported this, so this person can weigh in. I wouldn't be opposed to adding this URL to the "others" section if we added a note that conveys "we think offers listing only locations in Spain might be appropriate, but other offers are likely to not be good" adequately. If the original reporter wants to contact levels.fyi, I'm all for it- if not I can contact them myself.

**Comment by mobregozo** [comment]
Hey thanks for bringing this in, my idea behind sharing this link is to provide another source of information in regard to remote job openings in Spain.

I agree that filters might come up with false-positive results, very good point and I guess that's hard to control.
In terms of the contract, I honestly don't have much information, based on personal experience most of them offer a full-time contract by themselves or by third-party companies such as remote.com. 

I personally like this one as it's monitored, is updated quite often, and shows offers that are highly unlikely to show up on LinkedIn, plus not everyone is aware of its existence. This website got famous as per its salaries portal. 

My two cents. 

As a takeaway, I agree that adding it with a side note should be enough, but I leave that decision up to you.

**Comment by alexpdp7** [comment]
Sent them:

> I help maintain:
>
> https://github.com/remote-es/remotes
>
> , which intends to be a resource for Spaniards looking for remote jobs. There is a huge difference between remote offers; some companies have a Spanish entity, and offer regular full-time employee contacts, but some other companies only allow Spanish freelancers/contractors to work for them.
> We have found out that many people do not like becoming freelancers/contractors, and it is very hard to filter offers by this criteria in most job sites.
> Looking at your site:
>
> https://www.levels.fyi/jobs/location/spain?workArrangements=remote
> , many offers there are "Spain"-only, so seem very suitable for our site. However, on page two I see plenty of offers which list *many* countries, which "smell" like freelancing jobs.
> Do you have any indication of offers which "truly" hire in Spain? Maybe you can add such a feature or collect the data when companies post offers?
