### ISSUE TITLE
Investigate remote.com

### ISSUE THREAD

**Issue by alexpdp7** [remote-es/remotes#13]
https://remote.com/

They advertise Spanish hiring in Q1 2020. Need to check if their job board "guarantees" Spanish contracts.

**Comment by alexpdp7** [comment]
Sent an email to job@remote.com requesting info

**Comment by alexpdp7** [comment]
>> Recently I started:
>>
>> https://github.com/remote-es/remotes
>>
>> , where I list companies which hire people under full-time Spanish contracts following Spanish labor law. In Spain (and I'm sure many other places), working for foreign companies is painful, and thus most remote job boards are quite annoying to use- most of the offers are not interesting for people not wanting to go through the pains of working for foreign companies.
>>
>> I figured out that there aren't that many companies hiring remoties in Spain, so collecting a list of them looked feasible.
>>
>> I would like to know if your job boards have or will have any feature that will allow filtering offers from "companies using your services willing to hire people in Spain with full time contracts and remote work". This would be completely awesome, as it would be fantastic to address the problem I (and many others are having).

> That's a great idea. We do plan to integrate the two closely over time, so this fits into that.
> Spain is a hard country to operate in, even for us. We're still working on it, and have to do all sorts of extra work to be able to offer our services in Spain.

(so not yet)

**Comment by alexpdp7** [comment]
They now list Spain as Q2 2020. Q2 2020 ends in two weeks...

**Comment by uesteibar** [comment]
maybe we can close this and review in a few months?

**Comment by alexpdp7** [comment]
Sure, I was going to be strict and 20 days, but it's unlikely they'll make the Q2 target.

**Comment by alexpdp7** [comment]
https://remote.com/search?contract_type=Full%20time&location=Spain,%20Europe

Thoughts?

**Comment by alexpdp7** [comment]
Closing due to lack of feedback.
