### ISSUE TITLE
Consider adding issue/PR templates where people explicitly confirm new companies fulfill our conditions

### ISSUE THREAD

**Issue by alexpdp7** [remote-es/remotes#138]

**Comment by alexpdp7** [comment]
I have added:

* https://github.com/remote-es/remotes/blob/master/.github/ISSUE_TEMPLATE/add-new-company.md
* https://github.com/remote-es/remotes/blob/master/pull_request_template.md

as a prototype. @smoya feel free to propose changes/simplifications. My main concern is that those might be too complex and stop *legitimate* requests. I will close this no earlier than a month from now if there is no feedback.

**Comment by smoya** [comment]
> I have added:
> 
> * https://github.com/remote-es/remotes/blob/master/.github/ISSUE_TEMPLATE/add-new-company.md
> * https://github.com/remote-es/remotes/blob/master/pull_request_template.md
> 
> as a prototype. @smoya feel free to propose changes/simplifications. My main concern is that those might be too complex and stop _legitimate_ requests. I will close this no earlier than a month from now (Jan 31st) if there is no feedback.

I submitted a PR with few modifications https://github.com/remote-es/remotes/pull/160

**Comment by alexpdp7** [comment]
Merged your request, did a quick fix <https://github.com/remote-es/remotes/commit/3fa53a96f347c053b640cbdcf6d251fc7151225d>.

I think we can close this, thanks for the improvements!
