### ISSUE TITLE
Investigate YouGov

### ISSUE THREAD

**Issue by alexpdp7** [remote-es/remotes#21]
A personal acquaintance has been hired there, and he confirms he has a Spanish full-time employee contract, but their job listing is unclear on which positions are suitable for that.

**Comment by javiyt** [comment]
They have offices in Spain https://corporate.yougov.com/contact-us/global-offices/ and from their job descriptions:

> This is a full time, permanent remote role, which can be based in any worldwide YouGov Office or any remote location throughout the US or Europe.

**Comment by alexpdp7** [comment]
Yes. I just emailed them to see if there's an easy way to filter or find their offers which match this repo's criteria. I can make an educated guess by looking at:

https://jobs.yougov.com/jobs

But I'd rather have them confirm things like "all 'Anywhere, USA' offers allow hiring of people in Spain with a Spanish full-time employee contract" so we can clarify that in the listing (it's no fun to have to read all offers to filter the applicable ones).
