### ISSUE TITLE
Investigate https://trabajoenremoto.com/

### ISSUE THREAD

**Issue by alexpdp7** [remote-es/remotes#25]
@acroca @uesteibar I've just seen:

https://trabajoenremoto.com/

Looks very good, thoughts?

**Comment by acroca** [comment]
I don't think it mentions anything about the kind of contract, I'd assume some of them require the candidate to be freelancer but I'm not sure.
I guess we could add it with a note saying that only jobs located in Spain offer spanish contract, but would be good to confirm this with the admins of the site

**Comment by uesteibar** [comment]
> I guess we could add it with a note saying that only jobs located in Spain offer spanish contract

I'm not even sure that would be true, there could also be spanish companies looking for a freelancer there right?

**Comment by acroca** [comment]
It doesn't say. If we want to be strict with our list, I think we should either confirm with the admins about this topic or just don't show them

**Comment by uesteibar** [comment]
IMO, I don't think we should add every website that posts remote jobs in Spain, it could be too much noise. I'd rather stick to job boards that are Spain only.

**Comment by alexpdp7** [comment]
Well, I think those are Spain only (or at least I haven't seen offers for other countries), but they are not very clear. I've emailed them to see if there's a way to get a "good" job listing from them (i.e. that fulfills "our conditions"), let's see what they say.

(Personally, if some day LinkedIn or whomever allows filtering good offers, I'd be happy to close the repo when it no longer serves a purpose...)

**Comment by uesteibar** [comment]
let's wait and see what they get back to us with then :)

**Comment by alexpdp7** [comment]
I have sent you guys the emails through the emails accounts listed on your GitHub profile as I don't think it was appropriate to publish their answer in the open. If you are explicitly OK with it I can loop you in in further correspondence if you want to or whatever.

**Comment by uesteibar** [comment]
having looked at the email, I'd say we can add it as long as they can provide a link or set of instructions to find the kind of jobs we're looking for.

**Comment by alexpdp7** [comment]
Reached out to the maintainer again. Offers now seem pretty good for our criteria, but still not a good option to link to right now.

**Comment by alexpdp7** [comment]
No feedback, closing.
