### ISSUE TITLE
Refer a job posting service?

### ISSUE THREAD

**Issue by alexpdp7** [remote-es/remotes#32]
Just a thought.

I'm seeing a lot of companies posting job offers on static pages and weird stuff, which makes it bad for publishing here. I'm suspecting that many companies do so because they are tight on budget to publish job offers, use Bamboo or similar products, etc.

I think it would be good if we could point those companies to some place they could post those offers free of charge... in a way that works well with us. Either a place which would only publish offers matching our criteria or which would allow filtering.

Last resort would be to operate a mailing list. I'm happy to do that, but I'd rather look into something which already exists...

**Comment by acroca** [comment]
What about having a different section for specific jobs? We could require to add them with a date (like `[2020-04-27] Software engineer at Blah.`, this way people will understand some of they might not be valid anymore.

**Comment by alexpdp7** [comment]
Yeah, that could also work. I'm leaning towards *not* doing this ourselves because it might have bigger legal implications and "significant" maintenance overhead.

I've asked in the BcnEng Slack:

https://bcneng.slack.com/archives/C46K8J00L/p1591273077269200

, will probably ask in some other places to see if we can find anything existing. If there is nothing, I'm happy to try and tackle this ourselves.

**Comment by uesteibar** [comment]
yep, I'd rather not have it in the repo, but if we can find a reasonable and free option, I'm OK with referring to it 👍

**Comment by alexpdp7** [comment]
I only got referred to angel.co. They seem to be 0-cost and have a decent interface (you can filter by remote/Spain), but back when I looked at it, they didn't have a lot of offers.

Another option would be to send people to a Slack or similar community. I don't think BcnEng is the right place because it has a local scope, and checking:

https://comunidad-tecnologica.github.io/

They seem to have a good list of Slacks and similar, and they don't have anything.

I'm not a fan of Slack, but we could open a free one... but it sounds weird (and I'm not a big fan of Slack). I think it would make sense to do so if we wanted to start a community of remote developers in Spain, but personally, I don't feel I have time to do that.

Another option, I've been looking at Matrix. It's kinda like a free Slack. Matrix runs their own Matrix server, and we could create a channel there for remote offers. The good thing is that Matrix is completely open, and that lets you do a few interesting things:

* Integrate channels with other Slack instances: we could add the room to local Spanish Slacks like BcnEng
* Publish the offers outside Matrix, using RSS feeds, perhaps email, etc.

........

So the options for me without cost are:

* Send people to angel.co, perhaps link in our repo an angel.co search
* Find an existing Slack targetting Spain and ask for a channel to be created there (I know none)
* Create a Matrix channel on matrix.org, try to syndicate in other places
* Others (create a subreddit/Meneame/etc.?)

**Comment by uesteibar** [comment]
tbh, I don't see a bit value on referring elsewhere, I would personally go for

> Edit: an often overlooked solution to a problem: ignoring it

**Comment by alexpdp7** [comment]
Yeah, my thought was to have a solution to the problem of sending low-quality PRs, but I don't think there's a good solution. Closing for now.
