### ISSUE TITLE
Remove Factorial

### ISSUE THREAD

**Issue by alexpdp7** [remote-es/remotes#34]
They don't seem to offer remote any more.

**Comment by alexpdp7** [comment]
Pinging @oriolblanc , sending an email to info@factorial.co

**Comment by alexpdp7** [comment]
> I'm a maintainer of:
> https://github.com/remote-es/remotes
> , where we list companies offering remote positions with Spanish contracts. We checked:
> https://careers.factorialhr.com/
> but you don't seem to offer remote any more, so we will remove you from the listing, unless you confirm the offers listed there can be done remotely (not just during the pandemic). If you confirm, we would suggest you state that clearly on your careers website.

**Comment by oriolblanc** [comment]
Yes we do, I'm gonna change the Job Description to make it clearer!

**Comment by oriolblanc** [comment]
Updated. The offer now is `Fullstack Developer - Remote is ok!`

**Comment by alexpdp7** [comment]
Thanks. Closing the issue.

I would encourage you people to clarify your remote policy further in your website, to make it clearer that this is not a pandemic-related condition and that working fully remote is OK, etc. But I think it's good for now and we appreciate the prompt response.
