### ISSUE TITLE
Investigate remote.first

### ISSUE THREAD

**Issue by alexpdp7** [remote-es/remotes#56]
https://remotefirst.digital/empresas

**Comment by alexpdp7** [comment]
I had a chat with the owner of the website, and he  apparently has vetted all companies he lists, so he added the information about the kind of contracts they use:

https://remotefirst.digital/empresas/ofrecen-contrato-espanol

Which is pretty neat.

**Comment by IvanCoronado** [comment]
It could be cool if you add us to the list. I can also add more filters or features if you need them.

**Comment by alexpdp7** [comment]
We've added you to the list. As I took a look, one thing you might want to consider is adding "offers standard contract" as a main job search filter.

The reason we went with a company list here is because a company list is easier to get updated- but being able to browse offers is much better, @IvanCoronado
