### ISSUE TITLE
Consider jobfluent

### ISSUE THREAD

**Issue by alexpdp7** [remote-es/remotes#59]
https://www.jobfluent.com/es/empleos-remoto

Apparently companies listed there offer 100% remote and have offices in Spain. That doesn't necessarily imply they offer a standard contract, but I think it's very likely.

**Comment by uesteibar** [comment]
if a company has an office in Spain and hires remotely, I think we can asume that it's on a standard contract

**Comment by alexpdp7** [comment]
Added them :)
