### ISSUE TITLE
Consider adding "sync/async" information to the companies listing

### ISSUE THREAD

**Issue by alexpdp7** [remote-es/remotes#92]
On the BcnEng Slack, someone was asking about companies that hire on Spain, but are async enough so you could work as a digital nomad from a different country sporadically. Adding this information to the company listing would help people in this situation.

I feel making this information "mandatory" would be impractical- it would make vetting companies considerably harder, but surely we could request people to opt in to adding tags like "completely async", "UTC-2 - UTC+6 mandatory", etc.

**Comment by javiyt** [comment]
There are companies that is up to the team the way of working, so going for a timezone range would be better

**Comment by uesteibar** [comment]
I think timezone range would work best indeed

**Comment by alexpdp7** [comment]
What do you think about https://github.com/remote-es/remotes/pull/93 ?
